In [1]:
import numpy as np


In [6]:
dados = np.random.rand(2,3)

In [7]:
dados

array([[0.74306919, 0.31839324, 0.83360863],
       [0.54373026, 0.01669694, 0.6009415 ]])

In [8]:
dados.dtype

dtype('float64')

In [9]:
dados.shape

(2, 3)

In [10]:
dados.ndim

2

In [11]:
lista = [1,2,5,7.8,1.25]

In [12]:
dados2 = np.array(lista)

In [13]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [14]:
lista2 = [[1,2,3,4], [4,3,2,1]]

In [15]:
dados3 = np.array(lista2)

In [16]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [17]:
dadoszero = np.zeros(10)

In [18]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
dadoszero2 = np.zeros((2,3))

In [20]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
dadosum = np.ones(5)

In [22]:
dadosum

array([1., 1., 1., 1., 1.])

In [24]:
dadosseq = np.arange(10)

In [25]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
dadosseq2 = np.arange(0,20,2)

In [27]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
dadosseqf = dadosseq.astype(np.float64)

In [30]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
dadosseqf.dtype

dtype('float64')

Aritmética com Arrays

In [33]:
da4 = np.array([[1,2,3],[4,5,6]])

In [34]:
da4

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
da4*da4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [37]:
da4-da4

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
1/da4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [46]:
d5 = da4 + da4

In [47]:
d5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [40]:
da4

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
d5>da4

array([[ True,  True,  True],
       [ True,  True,  True]])

Indexação

In [49]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
dadosseq[5]

5

Diferente de uma lista python, um recorte (fatia) de ndarray sofrerá broadcast - é como se fosse uma view de banco de dados.

Com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [51]:
dadosseq[3:6]

array([3, 4, 5])

In [52]:
dadosseq[3:6]=20

In [53]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [54]:
fatia = dadosseq[2:4]

In [55]:
fatia

array([ 2, 20])

In [56]:
fatia[1]=2000

In [57]:
fatia

array([   2, 2000])

In [58]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [59]:
fatia[:]=333

In [60]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Copiar dados

In [61]:
f2 = dadosseq[2:4].copy()

In [62]:
f2[:]=111

In [63]:
f2

array([111, 111])

In [64]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Array com mais de uma dimensão

In [65]:
d6 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [66]:
d6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
d6[1:2]

array([[4, 5, 6]])

Máscaras

In [68]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [69]:
masc = (dadosseq < 100)

In [70]:
masc

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
dadosseq[dadosseq<20]=8888 

In [72]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

Transposição

In [73]:
d7 = np.arange(15).reshape((3,5))

In [74]:
d7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
d7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Multiplicação de matrzies com Dots

In [77]:
np.dot(d7.T, d7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])